<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediaDevices" Version="1.10.0" />
    <PackageReference Include="Nullable.Extended.Analyzer" Version="1.15.6581">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lyt.PhotoPostPro.MultiPlatformAbstractions\Lyt.PhotoPostPro.MultiPlatformAbstractions.csproj" />
  </ItemGroup>

</Project>
