<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>AVLN3001;</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>AVLN3001;</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="Avalonia">
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AvaloniaXamlVerboseExceptions>True</AvaloniaXamlVerboseExceptions>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Skia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageReference Include="Nullable.Extended.Analyzer" Version="1.15.6581">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="Assets\Images\**" />
    <AvaloniaResource Include="Assets\Languages\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Remove="Assets\Languages\Lang_bg-BG.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_bn-BD.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_de-DE.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_el-GR.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_en-US.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_es-ES.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_fr-FR.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_hi-IN.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_hu-HU.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_hy-AM.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_it-IT.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_jp-JP.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_ko-KO.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_uk-UA.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_zh-CN.axaml" />
    <AvaloniaResource Remove="Assets\Languages\Lang_zh-TW.axaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controls\Panels\SVirtualizingPanel.cs" />
    <Compile Remove="Controls\Panels\SVirtualizingStackPanel.cs" />
    <Compile Remove="Controls\Panels\SVirtualizingUniformGrid.cs" />
    <Compile Remove="Controls\Panels\SVirtualizingWrapPanel.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Languages\Lang_bg-BG.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_bn-BD.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_de-DE.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_el-GR.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_en-US.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_es-ES.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_fr-FR.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_hi-IN.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_hu-HU.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_hy-AM.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_it-IT.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_jp-JP.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_ko-KO.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_uk-UA.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_zh-CN.axaml" />
    <EmbeddedResource Include="Assets\Languages\Lang_zh-TW.axaml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Controls\Lyt.Avalonia.Controls.csproj" />
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Interfaces\Lyt.Avalonia.Interfaces.csproj" />
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Localizer\Lyt.Avalonia.Localizer.csproj" />
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Mvvm\Lyt.Avalonia.Mvvm.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.FileSystem\Lyt.FileSystem.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Framework.Interfaces\Lyt.Framework.Interfaces.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Model\Lyt.Model.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Mvvm\Lyt.Mvvm.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Persistence\Lyt.Persistence.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Utilities\Lyt.Utilities.csproj" />
    <ProjectReference Include="..\Lyt.PhotoPostPro.Model\Lyt.PhotoPostPro.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Workflow\Library\Dialogs\ProcessingDialog.axaml.cs">
      <DependentUpon>ProcessingDialog.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
