<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>AVLN3001;</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>AVLN3001;</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="Avalonia">
    <AvaloniaXamlVerboseExceptions>True</AvaloniaXamlVerboseExceptions>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Skia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageReference Include="Nullable.Extended.Analyzer" Version="1.15.6581">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="Assets\Images\**" />
    <AvaloniaResource Include="Assets\Languages\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controls\Panels\SVirtualizingPanel.cs" />
    <Compile Remove="Controls\Panels\SVirtualizingStackPanel.cs" />
    <Compile Remove="Controls\Panels\SVirtualizingUniformGrid.cs" />
    <Compile Remove="Controls\Panels\SVirtualizingWrapPanel.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Controls\Lyt.Avalonia.Controls.csproj" />
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Interfaces\Lyt.Avalonia.Interfaces.csproj" />
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Localizer\Lyt.Avalonia.Localizer.csproj" />
    <ProjectReference Include="..\..\Lyt.Avalonia\Lyt.Avalonia.Mvvm\Lyt.Avalonia.Mvvm.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.FileSystem\Lyt.FileSystem.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Framework.Interfaces\Lyt.Framework.Interfaces.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Model\Lyt.Model.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Mvvm\Lyt.Mvvm.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Persistence\Lyt.Persistence.csproj" />
    <ProjectReference Include="..\..\Lyt.Framework\Lyt.Utilities\Lyt.Utilities.csproj" />
    <ProjectReference Include="..\Lyt.PhotoPostPro.Model\Lyt.PhotoPostPro.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Workflow\Culling\CullingImageView.axaml.cs">
      <DependentUpon>CullingImageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Gallery\GalleryView.axaml.cs">
      <DependentUpon>GalleryView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Import\ImportView.axaml.cs">
      <DependentUpon>ImportView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Process\Lut\LutImageView.axaml.cs">
      <DependentUpon>LutImageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\Process\Lut\LutExplorerView.axaml.cs">
      <DependentUpon>LutExplorerView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
