rem this needs to be run using a start /wait command or else the web service will fail.  
rem
exit 0
rem To Run the translate server: 
rem			py -m libretranslate.main --port 5000 
rem
cd
cd %~p0
cd 
Lyt.Translator.Cli.exe PppLanguages.json
rem 
rem pause
cd 
exit 0
rem
rem 
rem Used Supported Languages Translated from English 
rem 
rem  Bengali (1.9) ...
rem  Bulgarian (1.9) ...
rem  Chinese (1.9) ...
rem  Chinese (traditional) (1.9) ...
rem 
rem  French (1.9) ...
rem  German (1.3) ...
rem  Greek (1.9) ...
rem  Hindi (1.1) ...
rem 
rem  Hungarian (1.9) ...
rem  Italian (1.0) ...
rem  Japanese (1.1) ...
rem  Korean (1.1) ...
rem 
rem  Portuguese (1.9) ...
rem  Spanish (1.0) ...
rem  Thai (1.9) ...
rem  Ukranian (1.4) ...
rem 
rem  Vietnamese (1.9) ...
rem 
rem 
rem Consider Supporting (Unused for now) 
rem 
rem  Polish (1.9) ...
rem  Esperanto (1.5) ...
rem  Indonesian (1.9) ...
rem  Tagalog (1.9) ...
rem 
rem All Supported Languages Unused for now
rem 
rem  Arabic (1.0) ...   Right to Left
rem  Hebrew (1.5) ...	Right to Left
rem  Persian (1.5) ...  Right to Left
rem 
rem 
rem  Albanian (1.9) ...
rem  Azerbaijani (1.5) ...
rem  Basque (1.9) ...
rem  Catalan (1.9) ...
rem  Czech (1.9.6) ...
rem  Danish (1.9) ...
rem  Dutch (1.8) ...
rem  Esperanto (1.5) ...
rem  Estonian (1.9) ...
rem  Finnish (1.9) ...
rem  Galician (1.9) ...
rem  Indonesian (1.9) ...
rem  Irish (1.1) ...
rem  Kyrgyz (1.4) ...
rem  Latvian (1.9) ...
rem  Lithuanian (1.9) ...
rem  Malay (1.9) ...
rem  Norwegian (1.9) ...
rem  Polish (1.9) ...
rem  Portuguese (Brazil) (1.9) ...
rem  Romanian (1.9) ...
rem  Russian (1.9) ...
rem  Slovak (1.9) ...
rem  Slovenian (1.9) ...
rem  Swahili (1.11) ...
rem  Swedish (1.5) ...
rem  Tagalog (1.9) ...
rem  Turkish (1.5) ...
rem  Urdu (1.9) ...
